version: '3'
services:
  app1:
    build: .
    container_name: app1
    restart: always

  app2:
    build: .
    container_name: app2
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx-1.27.0/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
